#!/bin/bash
FILE_PATH="${TRIM_APPDEST}/docker/docker-compose.yaml"
is_docker_running() {
    DOCKER_NAME=""
    if [ -f "$FILE_PATH" ]; then
        DOCKER_NAME=$(grep "container_name" "$FILE_PATH" | awk -F':' '{print $2}' | xargs)
    fi
    if [ -n "$DOCKER_NAME" ]; then
        docker inspect "$DOCKER_NAME" 2>/dev/null | grep -q '"Status": "running"' && return 0 || return 1
    fi
    return 1
}
case $1 in
start) exit 0 ;;
stop) exit 0 ;;
status) is_docker_running && exit 0 || exit 3 ;;
log)
    LINES="${2:-100}"
    [ -f "$FILE_PATH" ] && docker logs --tail "$LINES" "$(grep container_name "$FILE_PATH" | awk -F':' '{print $2}' | xargs)" 2>&1
    exit 0 ;;
*) exit 1 ;;
esac
